name: lionmiss-back

services:
  
  sql:
    image: mariadb:latest
    ports:
      - ${PORT_MARIA}:3306
    networks:
      - net-lionmiss-back
    environment:
      MARIADB_ROOT_PASSWORD: ${PASS_ROOT}
      MARIADB_DATABASE: ${DB}
      MARIADB_USER: ${USER_ADMIN}
      MARIADB_PASSWORD: ${PASS_USER_ADMIN}

  mongo:
    image: mongo:latest
    restart: always
    ports: 
      - ${PORT_MONGO}:27017
    volumes:
      - ./scripts/mongo:/docker-entrypoint-initdb.d
    networks:
      - net-lionmiss-back
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USER_ROOT}
      MONGO_INITDB_ROOT_PASSWORD: ${PASS_ROOT}
      MONGO_INITDB_DATABASE: ${DB}
      HOST_MONGO: ${HOST_MONGO}
      PORT_MONGO: ${PORT_MONGO}
      USER: ${USER}
      PASS_USER: ${PASS_USER}
      USER_ADMIN: ${USER_ADMIN}
      PASS_USER_ADMIN: ${PASS_USER_ADMIN}

networks:
  net-lionmiss-back:
    driver: bridge
    